spring.h2.console.enabled: true
          # 로그 형식으로 쿼리 보여주기

spring:
  jpa:
    properties:
      hibernate.format_sql: true  # 압축된 쿼리를 읽기 좋게 포멧

spring.jpa.hibernate.ddl-auto: create

spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    '[org.apache.coyote.http11]': DEBUG
    org.hibernate.SQL: debug


cloud:
  aws:
    credentials:
      accessKey: AKIARE5TNUV55SNW5HPQ
      secretKey: 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
    s3:
      bucket: cheoljunvucket
    region:
      static: ap-northeast-2
    stack:
      auto: false